import { FutureIncomeImpact } from "../lib/futureIncomeImpact";

type FutureIncomeImpactComparisonProps = { impact: FutureIncomeImpact; formatCurrency: (value: number) => string; hasFutureIncome: boolean };

export default function FutureIncomeImpactComparison({ impact, formatCurrency, hasFutureIncome }: FutureIncomeImpactComparisonProps) {
  if (!hasFutureIncome) return <section className="rounded-2xl border border-dashed border-slate-700 bg-slate-900 p-5"><h3 className="text-xl font-semibold">Future income impact</h3><p className="mt-2 text-sm text-slate-400">Add an enabled future income stream to compare how it could affect your Freedom Date.</p></section>;
  const years = (value: number | null) => value === null ? "Not reachable" : `${value} years`;
  return <section className="rounded-2xl border border-cyan-500/20 bg-slate-900 p-5" aria-labelledby="future-income-impact-heading"><h3 id="future-income-impact-heading" className="text-xl font-semibold">Future income impact</h3><p className="mt-2 text-sm text-slate-400">Future income is counted only from its configured start year.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><article className="rounded-xl border border-slate-800 bg-slate-950/60 p-4"><p className="text-xs uppercase tracking-[0.15em] text-slate-500">Without future income</p><p className="mt-3 text-lg font-semibold text-white">{years(impact.withoutIncome.years)}</p><p className="mt-1 text-sm text-slate-400">Estimated years remaining</p><p className="mt-3 text-sm text-slate-300">Target: {formatCurrency(impact.withoutIncome.projectedBalance)}</p></article><article className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 p-4"><p className="text-xs uppercase tracking-[0.15em] text-cyan-200">With future income</p><p className="mt-3 text-lg font-semibold text-white">{years(impact.withIncome.years)}</p><p className="mt-1 text-sm text-slate-300">Estimated years remaining</p><p className="mt-3 text-sm text-cyan-100">Years saved: {impact.yearsSaved === null ? "Not calculable" : impact.yearsSaved}</p></article></div><p className="mt-4 text-sm text-slate-300">{impact.yearsSaved !== null && impact.yearsSaved > 0 ? `Your future income could bring Freedom approximately ${impact.yearsSaved} years closer (${impact.percentageImprovement}% improvement in the estimated timeline).` : "Under these assumptions, future income does not change the estimated timeline."}</p></section>;
}
